### ISSUE TITLE
Unit Tests: Offline behaviour

### ISSUE THREAD

**Issue by VeronicaSalm** [CMPUT301F18T15/MediTrackr#12]
Should write tests to check that records / problems / profile information are being successfully saved and restored when the app closes. My bet is that there is a way to manually open and close the app from the testing method to confirm this.

**Comment by m-usman11** [comment]
https://github.com/CMPUT301F18T15/MediTrackr/commit/19d883ea3acea4990ba70e11e45adf381a257495
