### ISSUE TITLE
Unit Tests: ElasticSearch

### ISSUE THREAD

**Issue by VeronicaSalm** [CMPUT301F18T15/MediTrackr#13]
Write tests to show that saving and restoring to ElasticSearch is working correctly for all of the following:
- records and problems for a patient
- profile information
- associated patient lists for care providers

**Comment by m-usman11** [comment]
[Elastic Search JUnit Tests](https://github.com/CMPUT301F18T15/MediTrackr/commit/61c72699cc617b9caee46d6a6c467e4ce9a83e05)
