### ISSUE TITLE
Unit Tests: Searching

### ISSUE THREAD

**Issue by VeronicaSalm** [CMPUT301F18T15/MediTrackr#14]
Write unit tests for the code that will eventually search for records using:
- general keywords
- geo-location keywords
- body location
Tests should search for: something you know is present, something you know is not present, something that should return an error, etc.

**Comment by m-usman11** [comment]
[Searching JUnit Test](https://github.com/CMPUT301F18T15/MediTrackr/blob/master/app/src/androidTest/java/com/example/meditrackr/SearchingUnitTest.java)
