### ISSUE TITLE
Finish UML Relationships

### ISSUE THREAD

**Issue by chatterl** [CMPUT301F18T15/MediTrackr#19]

**Comment by m-usman11** [comment]
From https://github.com/CMPUT301F18T15/MediTrackr/issues/16:

Create at least one diagram of all the classes currently in the app. Extend this to any classes that we think should be present that are not currently (eg, perhaps we should have a BodyLocationPhoto class for storing information about body location photos). Should Activities be included?
--

**Comment by Skryt** [comment]
did not include getters/setters
