### ISSUE TITLE
Improve Release Planning

### ISSUE THREAD

**Issue by VeronicaSalm** [CMPUT301F18T15/MediTrackr#3]
Following comments from TA: 
- improve clarity,  streamline organization and group communication by delegating tasks and having explicit priorities for tasks (in case not everything expected to be completed by a given date can be)
- create timeline for functional and/or integration testing

**Comment by m-usman11** [comment]
[Release planning](https://github.com/CMPUT301F18T15/MediTrackr/wiki/Release-Planning) now incorporates testing plans and indicates task delegations to group members.
