### ISSUE TITLE
Unit Tests: CareProvider.java

### ISSUE THREAD

**Issue by VeronicaSalm** [CMPUT301F18T15/MediTrackr#6]
Implement unit tests for the methods in CareProvider.java. This includes:
getPatient, getPatients, setPatients

Also implement tests for the eventual functionality of this class:
add a patient to the list (not just setPatients, but add a single patient)

**Comment by m-usman11** [comment]
https://github.com/CMPUT301F18T15/MediTrackr/blob/master/app/src/androidTest/java/com/example/meditrackr/CareProviderTest.java

**Comment by m-usman11** [comment]
https://github.com/CMPUT301F18T15/MediTrackr/commit/19d883ea3acea4990ba70e11e45adf381a257495
