### ISSUE TITLE
Unit Tests: Patient.java

### ISSUE THREAD

**Issue by VeronicaSalm** [CMPUT301F18T15/MediTrackr#8]
Implement unit tests for the methods in Patient.java. This includes:
all getters and setters

Also implement tests for the eventual functionality of this class:
- should be able to call constructor of class without all contact information entered (ie, there should be default values for some of the parameters or we should implement multiple constructors?)

**Comment by chatterl** [comment]
started on this issue
https://github.com/CMPUT301F18T15/MediTrackr/blob/master/app/src/androidTest/java/com/example/meditrackr/PatientTest.java
