### ISSUE TITLE
Unit Tests: Problem.java

### ISSUE THREAD

**Issue by VeronicaSalm** [CMPUT301F18T15/MediTrackr#9]
Create unit tests for Problem.java's methods:
getTitle, setTitle, getDate, setDate,  getDescription, setDescription, getRecords, setRecords

Tests for additional functionality:
- should not be able to setDescription if the length is over 300 chars
- should not be able to setTitle if the length is over 30 chars
- should be able to add individual records of different types (Photo, comment, etc) so we probably want new getters and setters for that
- should be able to add a reminder schedule for a problem (Record Details: Use Case 6). This is currently not implemented but we should still make tests for it!

**Comment by m-usman11** [comment]
https://github.com/CMPUT301F18T15/MediTrackr/blob/master/app/src/androidTest/java/com/example/meditrackr/ProblemJUnitTest.java
